name: Read Rust File

on: [push]

jobs:
  read-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Rust file contents
      run: cat src/my_rust_code.rs
