name: Docker Action Example

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          docker build -t my-docker-image .
          docker run -v $PWD/hello-world-docker-action/src:/mnt my-docker-image
